name: "Check & Build"

on:
  push:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - run: nix flake check
      - run: nix build .#
